name: Build Clicker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Compile and build
      run: |
        export JAVA_HOME=$JAVA_HOME
        clang++ -c -fPIC -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/darwin" -std=c++17 Clicker.cpp -o Clicker.o
        clang++ -dynamiclib -fPIC -o libclicker.dylib Clicker.o -framework ApplicationServices
